
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - PB_ADMIN_EMAIL=nyimin.alt@gmail.com
      - PB_ADMIN_PASSWORD=nixcops5
    volumes:
      - ./pb_data:/pb_data
    command: serve --http 0.0.0.0:8090 --dir /pb_data

  web-map:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://api-grid.triunemyanmar.com
        - VITE_PVWATTS_API_KEY=6N1hfczKMYBxC1UrmBKJ2PkF1AChgP6dfOpOwyx9
    container_name: web-map
    restart: unless-stopped
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
